server:  
  port: ${PORT:2222}

spring:
  application:
    name: person-service
  datasource:
    url: jdbc:mysql://localhost:33306/datagrid?useSSL=false
    username: datagrid
    password: datagrid
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#      ddl-auto: create


#    properties:
#      hibernate:
#        show_sql: true
#        cache:
#          use_query_cache: true
#          use_second_level_cache: true
#          hazelcast:
#            instance_name: cache-1
#            use_native_client: true
#            native_client_address: 192.168.99.100
#            native_client_group: dev
#            native_client_password: dev-pass
#          region:
#            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

  testcontainers:
    beans:
      startup: parallel
#logging:
#  level:
#    com.hazelcast: DEBUG
#    org.hibernate: DEBUG